package example.mindorks.https.demo;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'janisharali' at '4/4/17 9:29 PM' with Gradle 3.1
 *
 * @author janisharali, @date 4/4/17 9:29 PM
 */
public class Application {

    public static void main(String[] argv) {

        SampleResponse response = ApiHandler.getSampleResponse();
        System.out.println(response);
    }
}
