/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'janisharali' at '4/4/17 9:29 PM' with Gradle 3.1
 *
 * @author janisharali, @date 4/4/17 9:29 PM
 */
public class ApplicationTest {

}
